#!/usr/bin/env python

import termios,sys

def getPass(prompt="Password: "):
  fd = sys.stdin.fileno()
  old = termios.tcgetattr(fd)
  new = termios.tcgetattr(fd)
  new[3] = new[3] & ~termios.ECHO
  try:
    termios.tcsetattr(fd, termios.TCSADRAIN, new)
    passwd = raw_input(prompt)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old)
  return passwd

print("\n"+getPass())
